2025-06-27 10:06:34,178 p=88728 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the 
the option `result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. 
This feature will be removed from community.general in version 13.0.0. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:06:34,729 p=88728 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] **************************************************************************************
2025-06-27 10:06:39,684 p=88728 u=jangkyungbin n=ansible INFO| TASK [ping] ************************************************************************************************
2025-06-27 10:06:39,685 p=88728 u=jangkyungbin n=ansible INFO| fatal: [master3]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.123". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.123' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.123: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:06:39,686 p=88728 u=jangkyungbin n=ansible INFO| fatal: [master1]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.121". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.121' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.121: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:06:39,686 p=88728 u=jangkyungbin n=ansible INFO| fatal: [worker2]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.132". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.132' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.132: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:06:39,755 p=88728 u=jangkyungbin n=ansible INFO| fatal: [worker1]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.131". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.131' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.131: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:06:39,761 p=88728 u=jangkyungbin n=ansible INFO| fatal: [master2]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.122". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.122' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.122: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:06:39,765 p=88728 u=jangkyungbin n=ansible INFO| PLAY RECAP *************************************************************************************************
2025-06-27 10:06:39,766 p=88728 u=jangkyungbin n=ansible INFO| master1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:06:39,766 p=88728 u=jangkyungbin n=ansible INFO| master2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:06:39,766 p=88728 u=jangkyungbin n=ansible INFO| master3                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:06:39,766 p=88728 u=jangkyungbin n=ansible INFO| worker1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:06:39,766 p=88728 u=jangkyungbin n=ansible INFO| worker2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:14:33,036 p=89849 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the 
the option `result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. 
This feature will be removed from community.general in version 13.0.0. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:14:33,082 p=89849 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] **************************************************************************************
2025-06-27 10:14:38,004 p=89849 u=jangkyungbin n=ansible INFO| TASK [ping] ************************************************************************************************
2025-06-27 10:14:38,005 p=89849 u=jangkyungbin n=ansible INFO| fatal: [worker1]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.131". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.131' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.131: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:14:38,030 p=89849 u=jangkyungbin n=ansible INFO| fatal: [master1]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.121". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.121' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.121: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:14:38,033 p=89849 u=jangkyungbin n=ansible INFO| fatal: [master3]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.123". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.123' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.123: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:14:38,033 p=89849 u=jangkyungbin n=ansible INFO| fatal: [master2]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.122". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.122' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.122: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:14:38,033 p=89849 u=jangkyungbin n=ansible INFO| fatal: [worker2]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "10.40.151.132". Make sure this host can be reached over ssh: Warning: Permanently added '10.40.151.132' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.132: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| PLAY RECAP *************************************************************************************************
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| master1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| master2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| master3                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| worker1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:14:38,035 p=89849 u=jangkyungbin n=ansible INFO| worker2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:15:16,289 p=89963 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the 
the option `result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. 
This feature will be removed from community.general in version 13.0.0. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:15:16,337 p=89963 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] **************************************************************************************
2025-06-27 10:15:21,166 p=89963 u=jangkyungbin n=ansible INFO| TASK [raw] *************************************************************************************************
2025-06-27 10:15:21,167 p=89963 u=jangkyungbin n=ansible INFO| fatal: [master2]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '10.40.151.122' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.122: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:15:21,167 p=89963 u=jangkyungbin n=ansible INFO| fatal: [master1]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '10.40.151.121' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.121: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:15:21,170 p=89963 u=jangkyungbin n=ansible INFO| fatal: [master3]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '10.40.151.123' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.123: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:15:21,232 p=89963 u=jangkyungbin n=ansible INFO| fatal: [worker1]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '10.40.151.131' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.131: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:15:21,334 p=89963 u=jangkyungbin n=ansible INFO| fatal: [worker2]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: Warning: Permanently added '10.40.151.132' (ED25519) to the list of known hosts.
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    root@10.40.151.132: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:15:21,335 p=89963 u=jangkyungbin n=ansible INFO| PLAY RECAP *************************************************************************************************
2025-06-27 10:15:21,335 p=89963 u=jangkyungbin n=ansible INFO| master1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:15:21,335 p=89963 u=jangkyungbin n=ansible INFO| master2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:15:21,336 p=89963 u=jangkyungbin n=ansible INFO| master3                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:15:21,336 p=89963 u=jangkyungbin n=ansible INFO| worker1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:15:21,336 p=89963 u=jangkyungbin n=ansible INFO| worker2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:16:08,889 p=90475 u=jangkyungbin n=ansible INFO| Using /Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/ansible.cfg as config file
2025-06-27 10:16:08,967 p=90475 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the 
the option `result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. 
This feature will be removed from community.general in version 13.0.0. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:16:09,031 p=90475 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] **************************************************************************************
2025-06-27 10:16:13,807 p=90475 u=jangkyungbin n=ansible INFO| TASK [raw] *************************************************************************************************
2025-06-27 10:16:13,808 p=90475 u=jangkyungbin n=ansible INFO| fatal: [master1]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.9p2, LibreSSL 3.3.6
    debug1: Reading configuration data /Users/jangkyungbin/.ssh/config
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
    debug1: /etc/ssh/ssh_config line 54: Applying options for *
    debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
    debug1: auto-mux: Trying existing master at '/tmp/ansible-ssh-10.40.151.121-22-root'
    debug1: Control socket "/tmp/ansible-ssh-10.40.151.121-22-root" does not exist
    debug1: Connecting to 10.40.151.121 [10.40.151.121] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa type -1
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_9.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
    debug1: compat_banner: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
    debug1: Authenticating to 10.40.151.121:22 as 'root'
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ssh-ed25519
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: SSH2_MSG_KEX_ECDH_REPLY received
    debug1: Server host key: ssh-ed25519 SHA256:aJM2sSftifNoLUGrlkPeleKf9wFQg6ynvT5kixaN6qw
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    Warning: Permanently added '10.40.151.121' (ED25519) to the list of known hosts.
    debug1: rekey out after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 134217728 blocks
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
    debug1: Next authentication method: publickey
    debug1: get_agent_identities: bound agent to hostkey
    debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
    debug1: Will attempt key: /Users/jangkyungbin/.ssh/id_rsa  explicit
    debug1: Trying private key: /Users/jangkyungbin/.ssh/id_rsa
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    debug1: No more authentication methods to try.
    root@10.40.151.121: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:16:13,847 p=90475 u=jangkyungbin n=ansible INFO| fatal: [worker1]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.9p2, LibreSSL 3.3.6
    debug1: Reading configuration data /Users/jangkyungbin/.ssh/config
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
    debug1: /etc/ssh/ssh_config line 54: Applying options for *
    debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
    debug1: auto-mux: Trying existing master at '/tmp/ansible-ssh-10.40.151.131-22-root'
    debug1: Control socket "/tmp/ansible-ssh-10.40.151.131-22-root" does not exist
    debug1: Connecting to 10.40.151.131 [10.40.151.131] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa type -1
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_9.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
    debug1: compat_banner: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
    debug1: Authenticating to 10.40.151.131:22 as 'root'
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ssh-ed25519
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: SSH2_MSG_KEX_ECDH_REPLY received
    debug1: Server host key: ssh-ed25519 SHA256:aJM2sSftifNoLUGrlkPeleKf9wFQg6ynvT5kixaN6qw
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    Warning: Permanently added '10.40.151.131' (ED25519) to the list of known hosts.
    debug1: rekey out after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 134217728 blocks
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
    debug1: Next authentication method: publickey
    debug1: get_agent_identities: bound agent to hostkey
    debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
    debug1: Will attempt key: /Users/jangkyungbin/.ssh/id_rsa  explicit
    debug1: Trying private key: /Users/jangkyungbin/.ssh/id_rsa
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    debug1: No more authentication methods to try.
    root@10.40.151.131: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:16:13,853 p=90475 u=jangkyungbin n=ansible INFO| fatal: [master3]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.9p2, LibreSSL 3.3.6
    debug1: Reading configuration data /Users/jangkyungbin/.ssh/config
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
    debug1: /etc/ssh/ssh_config line 54: Applying options for *
    debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
    debug1: auto-mux: Trying existing master at '/tmp/ansible-ssh-10.40.151.123-22-root'
    debug1: Control socket "/tmp/ansible-ssh-10.40.151.123-22-root" does not exist
    debug1: Connecting to 10.40.151.123 [10.40.151.123] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa type -1
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_9.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
    debug1: compat_banner: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
    debug1: Authenticating to 10.40.151.123:22 as 'root'
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ssh-ed25519
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: SSH2_MSG_KEX_ECDH_REPLY received
    debug1: Server host key: ssh-ed25519 SHA256:aJM2sSftifNoLUGrlkPeleKf9wFQg6ynvT5kixaN6qw
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    Warning: Permanently added '10.40.151.123' (ED25519) to the list of known hosts.
    debug1: rekey out after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 134217728 blocks
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
    debug1: Next authentication method: publickey
    debug1: get_agent_identities: bound agent to hostkey
    debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
    debug1: Will attempt key: /Users/jangkyungbin/.ssh/id_rsa  explicit
    debug1: Trying private key: /Users/jangkyungbin/.ssh/id_rsa
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    debug1: No more authentication methods to try.
    root@10.40.151.123: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:16:13,854 p=90475 u=jangkyungbin n=ansible INFO| fatal: [master2]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.9p2, LibreSSL 3.3.6
    debug1: Reading configuration data /Users/jangkyungbin/.ssh/config
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
    debug1: /etc/ssh/ssh_config line 54: Applying options for *
    debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
    debug1: auto-mux: Trying existing master at '/tmp/ansible-ssh-10.40.151.122-22-root'
    debug1: Control socket "/tmp/ansible-ssh-10.40.151.122-22-root" does not exist
    debug1: Connecting to 10.40.151.122 [10.40.151.122] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa type -1
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_9.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
    debug1: compat_banner: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
    debug1: Authenticating to 10.40.151.122:22 as 'root'
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ssh-ed25519
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: SSH2_MSG_KEX_ECDH_REPLY received
    debug1: Server host key: ssh-ed25519 SHA256:aJM2sSftifNoLUGrlkPeleKf9wFQg6ynvT5kixaN6qw
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    Warning: Permanently added '10.40.151.122' (ED25519) to the list of known hosts.
    debug1: rekey out after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 134217728 blocks
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
    debug1: Next authentication method: publickey
    debug1: get_agent_identities: bound agent to hostkey
    debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
    debug1: Will attempt key: /Users/jangkyungbin/.ssh/id_rsa  explicit
    debug1: Trying private key: /Users/jangkyungbin/.ssh/id_rsa
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    debug1: No more authentication methods to try.
    root@10.40.151.122: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:16:13,913 p=90475 u=jangkyungbin n=ansible INFO| fatal: [worker2]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.9p2, LibreSSL 3.3.6
    debug1: Reading configuration data /Users/jangkyungbin/.ssh/config
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
    debug1: /etc/ssh/ssh_config line 54: Applying options for *
    debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
    debug1: auto-mux: Trying existing master at '/tmp/ansible-ssh-10.40.151.132-22-root'
    debug1: Control socket "/tmp/ansible-ssh-10.40.151.132-22-root" does not exist
    debug1: Connecting to 10.40.151.132 [10.40.151.132] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa type -1
    debug1: identity file /Users/jangkyungbin/.ssh/id_rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_9.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
    debug1: compat_banner: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
    debug1: Authenticating to 10.40.151.132:22 as 'root'
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ssh-ed25519
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: SSH2_MSG_KEX_ECDH_REPLY received
    debug1: Server host key: ssh-ed25519 SHA256:aJM2sSftifNoLUGrlkPeleKf9wFQg6ynvT5kixaN6qw
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
    debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
    Warning: Permanently added '10.40.151.132' (ED25519) to the list of known hosts.
    debug1: rekey out after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 134217728 blocks
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
    debug1: Next authentication method: publickey
    debug1: get_agent_identities: bound agent to hostkey
    debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
    debug1: Will attempt key: /Users/jangkyungbin/.ssh/id_rsa  explicit
    debug1: Trying private key: /Users/jangkyungbin/.ssh/id_rsa
    no such identity: /Users/jangkyungbin/.ssh/id_rsa: No such file or directory
    debug1: No more authentication methods to try.
    root@10.40.151.132: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true
2025-06-27 10:16:13,913 p=90475 u=jangkyungbin n=ansible INFO| PLAY RECAP *************************************************************************************************
2025-06-27 10:16:13,913 p=90475 u=jangkyungbin n=ansible INFO| master1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:16:13,913 p=90475 u=jangkyungbin n=ansible INFO| master2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:16:13,914 p=90475 u=jangkyungbin n=ansible INFO| master3                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:16:13,914 p=90475 u=jangkyungbin n=ansible INFO| worker1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:16:13,914 p=90475 u=jangkyungbin n=ansible INFO| worker2                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-06-27 10:18:14,880 p=91094 u=jangkyungbin n=ansible WARNING| [WARNING]:  * Failed to parse
/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts with yaml plugin: We were
unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line
1 column 1 (char 0)  Syntax Error while loading YAML.   did not find expected <document start>. did not
find expected <document start>   in "<unicode string>", line 5, column 1  The error appears to be in
'/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts': line 5, column 1, but
may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:
[all:vars] ansible_user=root ^ here

2025-06-27 10:18:14,881 p=91094 u=jangkyungbin n=ansible WARNING| [WARNING]:  * Failed to parse
/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts with ini plugin:
/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts:27: Section
[k8s_cluster:vars] not valid for undefined group: k8s_cluster

2025-06-27 10:18:14,881 p=91094 u=jangkyungbin n=ansible WARNING| [WARNING]: Unable to parse /Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts
as an inventory source

2025-06-27 10:18:14,881 p=91094 u=jangkyungbin n=ansible WARNING| [WARNING]: No inventory was parsed, only implicit localhost is available

2025-06-27 10:18:14,884 p=91094 u=jangkyungbin n=ansible WARNING| [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does
not match 'all'

2025-06-27 10:18:14,927 p=91094 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the 
the option `result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. 
This feature will be removed from community.general in version 13.0.0. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:18:14,980 p=91094 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] **************************************************************************************
2025-06-27 10:18:14,985 p=91094 u=jangkyungbin n=ansible INFO| PLAY RECAP *************************************************************************************************
2025-06-27 10:22:46,283 p=91312 u=jangkyungbin n=ansible WARNING| [WARNING]:  * Failed to parse /Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts with yaml plugin: We
were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char 0)
Syntax Error while loading YAML.   did not find expected <document start>. did not find expected <document start>   in "<unicode
string>", line 5, column 1  The error appears to be in
'/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts': line 5, column 1, but may be elsewhere in the file
depending on the exact syntax problem.  The offending line appears to be:  [all:vars] ansible_user=root ^ here

2025-06-27 10:22:46,283 p=91312 u=jangkyungbin n=ansible WARNING| [WARNING]:  * Failed to parse /Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts with ini plugin:
/Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts:27: Section [k8s_cluster:vars] not valid for
undefined group: k8s_cluster

2025-06-27 10:22:46,284 p=91312 u=jangkyungbin n=ansible WARNING| [WARNING]: Unable to parse /Users/jangkyungbin/private/metanet/k8s/ansible/cluster_upgrade/inventory/hosts as an inventory source

2025-06-27 10:22:46,284 p=91312 u=jangkyungbin n=ansible WARNING| [WARNING]: No inventory was parsed, only implicit localhost is available

2025-06-27 10:22:46,286 p=91312 u=jangkyungbin n=ansible WARNING| [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2025-06-27 10:22:46,318 p=91312 u=jangkyungbin n=ansible INFO| [DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin has been superseded by the the option 
`result_format=yaml` in callback plugin ansible.builtin.default from ansible-core 2.13 onwards. This feature will be removed from 
community.general in version 13.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2025-06-27 10:22:46,358 p=91312 u=jangkyungbin n=ansible INFO| PLAY [Ansible Ad-Hoc] ****************************************************************************************************************
2025-06-27 10:22:46,362 p=91312 u=jangkyungbin n=ansible INFO| PLAY RECAP ***************************************************************************************************************************
